### ISSUE TITLE
Epic: Deterministic build support

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/sourcelink#601]
This issue is to track status of deterministic builds across the toolchain.

- [ ] https://github.com/dotnet/sourcelink/issues/572 - Workaround for pre 3.1.300 SDK's with fixes for AssemblyInfo file and TFM generated file
- [ ] https://github.com/dotnet/wpf/issues/1718 - WPF Markup Compiler
- [ ] https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/919 - CLI for Source Link validation tool

**Comment by tmat** [comment]
@jaredpar FYI

**Comment by clairernovotny** [comment]
@cartermp FYI

**Comment by richlander** [comment]
I'd like to see more preamble text that explains what this is for, and who will use it. Also, when all those boxes are checked, is the feature done? Or this is just the list that we currently know about / have issues.

As a format thing, the issue would be much easier to read if the text was hyperlinked, not just the issue #. That's what we do on the runtime repo.

**Comment by JamieMagee** [comment]
Is NuGet/Home#8601 also related?

**Comment by clairernovotny** [comment]
@JamieMagee Deterministic packing is not in scope for this as it's not necessary for validating that a binary came from the specified/published source.

**Comment by cartermp** [comment]
fyi @clairernovotny you can mark the F# item as checked now, thanks to @baronfel - https://github.com/dotnet/fsharp/pull/9874
